### ISSUE TITLE
RNMercadopagoModule is not abstract and does not override abstract method 

### ISSUE THREAD

**Issue by duataud** [shovelapps/react-native-mercadopago#1]
Hi, any help for this error with react-native 36 
node_modules/react-native-mercadopago/android/src/main/java/com/shovelapps/rnmercadopago/RNMercadopagoModule.java:50: error: RNMercadopagoModule is not abstract and does not override abstract method onActivityResult(Activity,int,int,Intent) in ActivityEventListener
public class RNMercadopagoModule extends ReactContextBaseJavaModule implements ActivityEventListener {

**Comment by schalela** [comment]
Hi @duataud, I think it was fixed in [https://github.com/shovelapps/react-native-mercadopago/commit/297d6b59e3c6559cd70f23ceb91b42c61e8bdb01](this commit). Please use RN 39.

Closing.
