### ISSUE TITLE
dyld: Library not loaded: @rpath/libswiftQuartzCore.dylib

### ISSUE THREAD

**Issue by codingwaysarg** [shovelapps/react-native-mercadopago#2]
Hi! Im getting this issue after compiling successfuly my app on IOS. When the emulator runs the app, it shows this message:

dyld: Library not loaded: @rpath/libswiftQuartzCore.dylib
  Referenced from: /Users/codingways/Library/Developer/CoreSimulator/Devices/8BB774D6-EA41-4CA2-805F-EF171384D013/data/Containers/Bundle/Application/89454ADB-B5C9-4B00-937A-638079E581F2/quierofotos.app/Frameworks/MercadoPagoSDK.framework/MercadoPagoSDK
  Reason: image not found
(lldb)

After this, the app crashes. On Android, everything works great... Any clues?

Thanks a lot!

**Comment by schalela** [comment]
What version of React Native are you using?
